export const LEVELS = [
  {
    number: 1,
    name: 'Tutorial',
    requiredOutput: 500,
    timeLimitSeconds: 120,
    startingBlocks: [{ type: 'base', count: 1 }],
    startingPixels: { white: 20 },
    tutorial: true,
  },
  {
    number: 2,
    name: 'Color Lab',
    requiredOutput: 1200,
    timeLimitSeconds: 150,
    startingBlocks: [{ type: 'base', count: 2 }],
    startingPixels: { white: 15, red: 5, blue: 5, yellow: 5 },
  },
  {
    number: 3,
    name: 'Double Down',
    requiredOutput: 2500,
    timeLimitSeconds: 180,
    startingBlocks: [{ type: 'base', count: 2 }, { type: 'doubler', count: 1 }],
    startingPixels: { white: 20, red: 10, blue: 10, yellow: 10 },
  },
  {
    number: 4,
    name: 'Crossfire',
    requiredOutput: 4000,
    timeLimitSeconds: 200,
    startingBlocks: [{ type: 'base', count: 3 }, { type: 'cross_amp', count: 1 }],
    startingPixels: { white: 20, red: 10, blue: 10, yellow: 10, green: 10 },
  },
  {
    number: 5,
    name: 'Color Theory',
    requiredOutput: 7000,
    timeLimitSeconds: 220,
    startingBlocks: [
      { type: 'base', count: 3 },
      { type: 'doubler', count: 1 },
      { type: 'color_checker', count: 1 },
    ],
    startingPixels: { white: 20, red: 15, blue: 15, yellow: 15, green: 15 },
  },
  {
    number: 6,
    name: 'Gold Rush',
    requiredOutput: 12000,
    timeLimitSeconds: 240,
    startingBlocks: [
      { type: 'base', count: 3 },
      { type: 'doubler', count: 1 },
      { type: 'cross_amp', count: 1 },
      { type: 'greedy', count: 1 },
    ],
    startingPixels: { white: 20, red: 20, blue: 20, yellow: 20, green: 20 },
  },
  {
    number: 7,
    name: 'Set Puzzle',
    requiredOutput: 20000,
    timeLimitSeconds: 260,
    startingBlocks: [
      { type: 'base', count: 4 },
      { type: 'doubler', count: 1 },
      { type: 'cross_amp', count: 1 },
      { type: 'color_checker', count: 1 },
    ],
    startingPixels: { white: 20, red: 20, blue: 20, yellow: 20, green: 40 },
    hint: 'Try making a GRASS set block! (Yellow + Green, 30+ pixels)',
  },
  {
    number: 8,
    name: 'Synergy',
    requiredOutput: 35000,
    timeLimitSeconds: 280,
    startingBlocks: [
      { type: 'base', count: 4 },
      { type: 'doubler', count: 2 },
      { type: 'cross_amp', count: 1 },
      { type: 'color_checker', count: 1 },
    ],
    startingPixels: { white: 20, red: 30, blue: 30, yellow: 30, green: 30 },
  },
  {
    number: 9,
    name: 'Dominance',
    requiredOutput: 60000,
    timeLimitSeconds: 300,
    startingBlocks: [
      { type: 'base', count: 5 },
      { type: 'doubler', count: 2 },
      { type: 'cross_amp', count: 2 },
      { type: 'color_checker', count: 1 },
    ],
    startingPixels: { white: 20, red: 40, blue: 40, yellow: 40, green: 20 },
    hint: 'Fill one block with 50%+ of a single color to dominate all 8 neighbors!',
  },
  {
    number: 10,
    name: 'Full Factory',
    requiredOutput: 100000,
    timeLimitSeconds: 330,
    startingBlocks: [
      { type: 'base', count: 6 },
      { type: 'doubler', count: 2 },
      { type: 'cross_amp', count: 2 },
      { type: 'color_checker', count: 1 },
      { type: 'greedy', count: 1 },
    ],
    startingPixels: { white: 20, red: 50, blue: 50, yellow: 50, green: 30 },
  },
]

export function getLevelConfig(levelNumber) {
  return LEVELS.find(l => l.number === levelNumber) || null
}
